-- RaportRBR v1.0 — Schema bazy danych
-- Wykonaj ten plik raz po utworzeniu bazy na Railway

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  code VARCHAR(30) UNIQUE NOT NULL,
  name VARCHAR(150) NOT NULL,
  password_hash VARCHAR(100) NOT NULL,
  must_change_password BOOLEAN DEFAULT TRUE,
  role VARCHAR(20) DEFAULT 'worker',
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS reports (
  id SERIAL PRIMARY KEY,
  worker_code VARCHAR(30) NOT NULL REFERENCES users(code) ON DELETE CASCADE,
  report_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS report_lines (
  id SERIAL PRIMARY KEY,
  report_id INTEGER NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  project VARCHAR(10) NOT NULL,
  product INTEGER NOT NULL,
  stage VARCHAR(10) NOT NULL,
  contractor_code VARCHAR(30),
  note TEXT DEFAULT '',
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS email_recipients (
  id SERIAL PRIMARY KEY,
  email VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reports_worker ON reports(worker_code);
CREATE INDEX IF NOT EXISTS idx_reports_date ON reports(report_date);
CREATE INDEX IF NOT EXISTS idx_lines_report ON report_lines(report_id);
CREATE INDEX IF NOT EXISTS idx_lines_project ON report_lines(project, product);

-- Konto głównego administratora (hasło: admin1234)
INSERT INTO users (code, name, password_hash, must_change_password, role)
VALUES ('ADMIN', 'Administrator', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', FALSE, 'manager')
ON CONFLICT (code) DO NOTHING;

-- Wszyscy pracownicy z hasłem tymczasowym "zmien123"
-- $2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2. = bcrypt("zmien123")
INSERT INTO users (code, name, password_hash, must_change_password, role) VALUES
('PLY157', 'Buciak Artur', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET120', 'Hrydzhuk Andrii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET092', 'Klimashevskyi Andrii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ELE003', 'Flak Lukasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PRZ006', 'Jurczyk Waldemar', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA015', 'PRIMO FHU', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN099', 'Lazutchyk Bohdan', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA011', 'HARTWIG C.', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY156', 'Pieńkowski Dariusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL005', 'Slusarczyk Piotr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL006', 'Joniec Rafal', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL009', 'Brzusko Tobiasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL017', 'Skowron Bartosz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL018', 'Langner Darian', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL025', 'Dolecki Norbert', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL027', 'Plata Tomasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL028', 'Wardęga Grzegorz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL029', 'Radzik Grzegorz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL030', 'Myśliniecki Sergiusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL031', 'Charnau Raman', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL044', 'Mikolajczuk Maciej', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL043', 'Marzol Mateusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL042', 'Kuska Dominik', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL041', 'Makowiecki Krystian', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL040', 'Volyk Natalia', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL039', 'Szakiel Marcin', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL038', 'Radzik Ewelina', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL037', 'Kobański Dawid', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL036', 'Chrobak Roksana', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN066', 'Wilkosz Dawid', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM092', 'Kiptilyi Denys', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM080', 'Lohvinenko Dmytro', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR043', 'Duvak Mikulas', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET085', 'Taran Eduard', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PRZ009', 'Kieblesz Dariusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA018', 'FEBO Logistic', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN041', 'Kopański Filip', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY086', 'Pawelec Andrzej', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN037', 'Streibel Kamil', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN006', 'Izba Rafal', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN009', 'Piszczek Adam', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM095', 'HONCHAROV IHOR', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET179', 'Ghosh Bharat', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET155', 'Hapak Ivan', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET033', 'Yakymenko Ivan', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY074', 'Ostrowski Przemysław', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET195', 'Ciotkowski Kamil', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET133', 'Tereshchuk Maksym', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR001', 'Kuźmiak Marek', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY084', 'Niedzielski Marek', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TYN036', 'Zohrap Tsaturyan', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET189', 'MYKULTSIA MYKHAILO', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM085', 'Trush Oleksandr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET045', 'Smirnov Maksim', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET146', 'Batarin Oleksandr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN057', 'Ipatenko Oleksandr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN080', 'Kiapp Oleksandr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET047', 'Marchuk Oleksandr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL045', 'Mielecki Michał', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL054', 'Mielecka Marzena', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL053', 'Mielecki Jacek', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL052', 'Kwieciński Kamil', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL051', 'Prokopek Kamil', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL050', 'Suszyło Paweł', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL049', 'Marzec Arkadiusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET182', 'Liakh Pavlo', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA003', 'Pawbol Logistyka', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('IZO051', 'Zajdel Piotr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('FUG025', 'Brach Jan', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ZAL005', 'Pędziwiatr Rafał', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PRZ002', 'Domeradzki Henryk', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET004', 'KRZYŻANIAK ROBERT', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET008', 'Mazurkiewicz Grzegorz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET011', 'Goldyn Wojciech', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PRZ005', 'Ros Marcin', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('IZO008', 'Skarbowski Piotr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN025', 'Brzeziński Patryk', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('KON005', 'Janicki Jacek', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET035', 'Serhii Lysenko', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET036', 'Lysenko Anatolii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SIL010', 'Tomasz Piechota', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET041', 'Krechko Vitalii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET042', 'Lukovets Vitalii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET056', 'Soboliev Ihor', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('KON008', 'Szałęga Maciej', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('KON011', 'Kowalik Dorota', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SPR015', 'Adamska Dagmara', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET094', 'Salaiev Ivan', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET104', 'Soboliev Viktor', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET105', 'Stepantsov Petro', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET107', 'Zelek Łukasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET117', 'Ptaszyński Dariusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET141', 'Łysakowski Sebastian', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET142', 'Samczyński Marcin', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET150', 'Oliinyk Volodymyr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM005', 'Stuchkov Serhii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM006', 'Stuchkov Yurii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM024', 'Bezrukov Oleksandr', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN100', 'Jarosz Norbert', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR002', 'Guss Grzegorz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR003', 'Randak Zbigniew', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR004', 'Korpaczewski Bartosz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET153', 'Biernacki Damian', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR005', 'Biernat Patrycja', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET157', 'Korowajczyk Mateusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET162', 'Nesteruk Oleh', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ROZ002', 'Rejek Łukasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ROZ003', 'Rywudzki Krzysztof', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SPR024', 'Hauza Angelika', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET163', 'Szynal Jarosław', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('FUG033', 'Smirnova Liliia', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM094', 'Bobyr Yurii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('KON023', 'Skarbowska Aneta', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR153', 'Hovzan Mariia', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('KON024', 'Kobiałka Natalia', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET184', 'SHOVKOPLIAS HRYHORII', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN128', 'Jasiński Paweł', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET191', 'Jankowiak Michał', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET192', 'SOBOLIEV IHOR', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM110', 'NIKITENKO NATALIIA', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL046', 'Depta Paweł', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('MAL047', 'Kuza Michał', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ELE021', 'Sławiński Bartłomiej', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR154', 'Pominięty 2 Leszek', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ELE018', 'Rębisz Jarosław', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN139', 'Dobrowolski Lukasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ELE029', 'Garbera Patryk', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SPR038', 'Kurgan Aleksandra', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SPR039', 'Bobyr Larysa', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET200', 'NASADIUK DMYTRO', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET201', 'HRAZHДАНKIN ROMAN', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET202', 'Kuczyński Mateusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET203', 'Serokos Mateusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('FUG051', 'Czernik Damian', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('RBR178', 'Kuryło Michał', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY171', 'Puścian Marek', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN083', 'Astafiev Kostiatyn', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SPR019', 'Astafieva Regina', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA009', 'RITEX LOGISTICS SP Z O O', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM030', 'Feniak Roman', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY037', 'Morozov Roman', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN001', 'Cimoszyński Sergiusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN003', 'Smola Marcin', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN004', 'Mrugala Marcin', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN032', 'Krzesiński Adam', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY078', 'Liubenko Serhii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('POM082', 'Urban Paweł', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PRZ008', 'Sadowski Łukasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET172', 'Tryka Tomasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA017', 'CHAPŃSKI MAREK', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA002', 'Kaczmarek Robert', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA005', 'ROGOZIŃSKI WOJCIECH', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SZL044', 'Flores Jimys', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ELE011', 'Rus Klemens', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ELE014', 'Krząstek Radosław', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY135', 'Filipczyk Dariusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY077', 'Mazur Marcin', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('FUG028', 'Rayska Sylwia', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('FUG031', 'Zygmunt Mateusz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SIL019', 'Staszków Andrzej', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TRA012', 'Dąbrowska Małgorzata', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('FUG046', 'Kalysh Vasyl', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET051', 'Mykultsia Vasyl', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('TYN006', 'Okhremchuk Vasyl', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('ZAL004', 'Trubchak Viktor', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SKL008', 'Homeniuk Vitalii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN015', 'POSTEBAILO MAKSYM', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET187', 'Riaboshapko Vitalii', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN058', 'YERMOLOV VITALII', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('PLY075', 'Kopyshchyk Vladyslav', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SIL011', 'Kucy Tomasz', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN135', 'Denes Wojciech', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('SAN108', 'KONDRATIEV YEVHENII', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker'),
('BET188', 'MYKULTSIA YURII', '$2a$10$rBV2JDeWW3.vKyeQcM5BreBBvFBPGnqjFAFKjBjdoyRj3hEUoNP2.', TRUE, 'worker')
ON CONFLICT (code) DO NOTHING;
